### ISSUE TITLE
HOMER Version?

### ISSUE THREAD

**Issue by airsay** [hepictel/hepic-voipmonitor#12]
Was this ever pushed to HOMER?

**Comment by lmangani** [comment]
No need to. The HEPSub feature is exactly the same in HOMER (minus the UI parts). Have you tried it?

**Comment by airsay** [comment]
I haven't tried it yet, primarily because I am unsure how to. Spin up a VM, install docker and docker-compose, then deploy this? I currently have a homelab setup with the VoIP server sendin hep data to my existin Homer 7. How would I replicate this with HEPSub

**Comment by lmangani** [comment]
This is probably a better starting point: https://github.com/sipcapture/hepsub-voipmonitor
